export const projects = [
  {
    name: "Top 5 Passive Income Streams For Financial Independence",
    categories: ["Top 5", "Cash Cow", "Finance"],
    img: "https://i.postimg.cc/VNkrgtd2/Top-5-motivation-movies.png",
    link: "https://www.youtube.com/watch?v=GLS5j0nsrC8&t=95s",
    delay: 0.2,
  },
  {
    name: "The Worst Investment Mistakes That You May Ever Make in 2023",
    categories: ["Finance", "Cash Cow"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=93JSb42DfZk&t=7s",
    delay: 0.4,
  },
  {
    name: "Google's Gemini is Taking Over The World?? No Way!!!",
    categories: ["AI News"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=CRjBkEDR7jI",
    delay: 0.6,
  },
  {
    name: "A Young Man Enters A High School Tournament",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/JzBdnyrV/matilda-2.png",
    link: "https://www.youtube.com/watch?v=1qkQoYTFxd4&t=6s",
    delay: 0.2,
  },
  {
    name: "When A Game Becomes A matter Of Life or Death",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/8PvCmHw7/Story-Book.png",
    link: "https://www.youtube.com/watch?v=DxPV-tMIZYQ&t=74s",
    delay: 0.4,
  },
  {
    name: "How AI will take over HUMANITY ⚠️ 2033",
    categories: ["AI News"],
    img: "https://i.postimg.cc/L5NGzG7c/top-passive-income.png",
    link: "https://www.youtube.com/watch?v=kJd8aBEwNss&t=49s",
    delay: 0.6,
  },
  {
    name: "Reveal The Epic Rise Of a Hero",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/VNkrgtd2/Top-5-motivation-movies.png",
    link: "https://www.youtube.com/watch?v=a30mPC4Hx2s&t=64s",
    delay: 0.2,
  },
  {
    name: "The Mysterious Reincarnated Man Who Rises as a Fearsome Demon Slayer",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=mnben-qZk9g",
    delay: 0.4,
  },
  {
    name: "The Journey Of The Unknown HERO To Reach the Top and Find His Sister",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=CvVvwqkn4FU",
    delay: 0.6,
  },
  {
    name: "Meet the Mind-Blowing War Genius Who Crafts Strategies While sleeping",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/VNkrgtd2/Top-5-motivation-movies.png",
    link: "https://www.youtube.com/watch?v=Qm9M9I8zy-E",
    delay: 0.2,
  },
  {
    name: "The Overpowered Boy Unleashes His Mighty Powers to Defeat Demons",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=ZC1o0pd9Thc",
    delay: 0.4,
  },
  {
    name: "This STRANGE MAN becomes the most POWERFUL LORD in the WORLD",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=itk2vebUyL8&t=54s",
    delay: 0.6,
  },
  {
    name: "A tiny little GIRL becomes the most POWERFUL person in the world",
    categories: ["Recaps"],
    img: "https://i.postimg.cc/VNkrgtd2/Top-5-motivation-movies.png",
    link: "https://www.youtube.com/watch?v=k4TE2idmbDA",
    delay: 0.2,
  },
  {
    name: "Love Beyond Borders: Cross-Cultural Romances of the Roaring Twenties",
    categories: ["History"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=mC2V7glFi3k",
    delay: 0.4,
  },
  {
    name: "Pope John XII's Reign of Infamy",
    categories: ["History"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=K6yx053CNG8&t=48s",
    delay: 0.6,
  },
  {
    name: "Exploring the Untold Horrors of Genghis Khan's Reign",
    categories: ["History"],
    img: "https://i.postimg.cc/VNkrgtd2/Top-5-motivation-movies.png",
    link: "https://www.youtube.com/watch?v=rGs4bcU3Rko&t=48s",
    delay: 0.2,
  },
  {
    name: "Love Beyond Controversial Marriages",
    categories: ["History"],
    img: "https://i.postimg.cc/XqH9KggH/AI-thumbnail.jpg",
    link: "https://www.youtube.com/watch?v=nDk32Qo8N2U&t=22s",
    delay: 0.4,
  },
];
